---
name: CI

'on':
  - push
  - pull_request

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --parallel

  test:
    name: "${{matrix.ruby}} ${{matrix.gemfile}} ${{matrix.os || 'ubuntu-latest'}}"
    env:
      CI: true
    runs-on: ${{matrix.os || 'ubuntu-latest'}}
    continue-on-error: "${{matrix.experimental || false}}"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby-2.7
          - ruby-3.0
          - ruby-3.1
          - ruby-3.2
          - ruby-3.3
          - ruby-3.4
          - jruby-9.4
          - truffleruby
        gemfile:
          - rails70
          - rails71
          - rails72
          - rails80
          - master
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        exclude:
          - ruby: truffleruby
            os: windows-latest

    steps:
      - name: repo checkout
        uses: actions/checkout@v3
      - name: load ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GEMFILE: "spec/gemfiles/Gemfile.${{matrix.gemfile}}"
        with:
          ruby-version: "${{matrix.ruby}}"
      - name: bundle
        env:
          BUNDLE_GEMFILE: "spec/gemfiles/Gemfile.${{matrix.gemfile}}"
        run: bundle install --jobs 4 --retry 3
      - name: test
        timeout-minutes: 60
        continue-on-error: "${{matrix.experimental || false}}"
        env:
          BUNDLE_GEMFILE: "spec/gemfiles/Gemfile.${{matrix.gemfile}}"
        run: bundle exec rake spec
